### ISSUE TITLE
Hive 50070 port missing from README

### ISSUE THREAD

**Issue by sunny0826** [datastrato/gravitino-playground#41]
In the Hive service started by docker compose, a total of 4 ports are started: `3307` `9000` `9083` `50070`, but only 3 are stated in the README.

```yaml
# docker-compose.yaml
services:
  hive:
    image: datastrato/hive:2.7.3-no-yarn
    ports:
      - "3307:3306"
      - "9000:9000"
      - "9083:9083"
      - "50070:50070"
    container_name: playground
...
```
